### PR TITLE
chore(pom): [IN-1083] update testcontainers version to 2.0.3 and quarkus to 3.33.1 LTS

### PR DESCRIPTION
**Pull request by frisonisland**
- least compatible with docker 29+
- does not need to define docker api.version (testcontainers 1.21+ needs api.version=1.44 to work with docker 29+)
- upgraded jenkins-lib-common to 1.7.0 (1.6.2 calls a docker info which times out)

Read the AI generated comment, because the compatibility matrix is quite hard to understand

### CODE REVIEW

**Comment by frisonisland** [comment]
### Quarkus / Testcontainers / docker-java compatibility matrix

This is the combination space we explored while bumping these dependencies. The cell shows the `docker-java-api` version Maven actually resolves and whether tests that use Testcontainers run.

| `quarkus-bom` | `testcontainers-bom` | Resolved `docker-java-api` | Works? |
|---|---|---|---|
| 3.30.6 | 2.0.5 | 3.4.2 (from quarkus-bom) | No — `NoClassDefFoundError: ImageHistoryCmd` |
| 3.33.1 (LTS) | 2.0.5 | 3.7.0 (from quarkus-bom) | No — same `ImageHistoryCmd` error |
| 3.33.1 (LTS) | 2.0.5 + explicit `docker-java` 3.7.1 pin | 3.7.1 | Yes |
| 3.34.x | 2.0.5 | 3.7.1 (from quarkus-bom) | Yes — no override needed |
| **3.33.1 (LTS)** | **2.0.3** | 3.7.0 (from quarkus-bom) | **Yes — chosen here** |

Notes:
- `testcontainers-bom` does not manage `docker-java` versions, so `quarkus-bom` always wins for that artifact.
- `testcontainers-consul:2.0.5` calls `ImageHistoryCmd`, which was added in `docker-java` 3.7.1; 2.0.3 does not, so it works fine with the 3.7.0 that 3.33 LTS ships.
- We're sticking with the LTS line, so the cleanest combo is **Quarkus 3.33.1 + testcontainers-bom 2.0.3**, which needs no extra pins.

**Review by M0Rf30 — APPROVED** [review]
